spring.application.name=backend-IP
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=jdbc:mysql://localhost:3306/${DATABASE_NAME}
spring.datasource.username=${SQL_USER}
spring.datasource.password=${SQL_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.ai.mcp.server.name=investment-tracker-mcp
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.protocol=STREAMABLE

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini